global:
  save_path: ./output

model:
  name: Qwen
  model_path: Qwen/Qwen3-4B
  trust_remote_code: true
  torch_dtype: auto
  device_map: auto
  low_cpu_mem_usage: true
  use_cache: false

compression:
  name: QAT
  quantization:
    ignore_layers: ["lm_head", "embed_tokens"] # Skip quantization for these layers
  QAT:
    hf_dataset: Salesforce/wikitext,wikitext-2-raw-v1 # hf dataset name, will overwrite dataset.data_path
    # hf_cache_dir: Specify your cache path, or not set(default)
    training_mode: end2end
    dist_mode: hf # "hf" is using hf Trainer
    save_format: fake # Set "fake" or "real", or not set(skip save)
    do_train: true
    # resume_ckpt_dir: Resume for fake checkpoint, when save_format=='fake', or not set
    plugin_config:
      enable_scale: true
      quant_config:
        use_weight_quant: true
        use_activation_quant: false
        weight: # can overwrite compression.quantization
          qtype: int4
          granularity: per-group
          group_size: 128
          is_sym: true
    hf_args: # hf trainer args
      # output_dir: Not to set, same as global.save_path
      # other arguments, see https://huggingface.co/docs/transformers/v5.1.0/en/main_classes/trainer#transformers.Seq2SeqTrainingArguments

dataset:
  name: TextDataset
  data_path: ./dataset/sharegpt_gpt4_qwen/sharegpt_gpt4-qwen3_a22B_output.jsonl
  max_seq_length: 2048
  num_samples: 256
  batch_size: 1

